### ISSUE TITLE
stereo support

### ISSUE THREAD

**Issue by Commandcracker** [Commandcracker/YouCube#19]
add stereo / multiple speaker support

**Comment by Commandcracker** [comment]
stereo will not be added!
But multiple speaker support will be.

**Comment by TheAlan404** [comment]
I implemented multiple speaker support by modifying the code - it is possible

Though i wish i didnt delete it now lmao, it does work using the parallel api but it was a mess in the code (making functions for every speaker with the buffer and also passing them to the parallel api)
