### ISSUE TITLE
sanjuuni support

### ISSUE THREAD

**Issue by Commandcracker** [Commandcracker/YouCube#25]
add support for [sanjuuni](https://github.com/MCJack123/sanjuuni) image and video formats

**Comment by Apethesis** [comment]
i feel like it wouldnt be too good of an idea cause of the needed resources
if a lot of people stream video at the same time then it just becomes sluggish as heck

**Comment by Commandcracker** [comment]
> i feel like it wouldnt be too good of an idea cause of the needed resources if a lot of people stream video at the same time then it just becomes sluggish as heck

This could happen. Restricting the usage of sanjuuni with a whitelist would probably fix that and if someone is not whitelisted but want's to use sanjuuni thy could create their own server. Also the [repeat-function](https://github.com/Commandcracker/YouCube/issues/36) could mitigate the usage of sanjuuni.

**Comment by Apethesis** [comment]
Either a whitelist or a configurable queue
