### ISSUE TITLE
Queue events to be pulled from other programs

### ISSUE THREAD

**Issue by TheAlan404** [Commandcracker/YouCube#56]
### Describe the feature.

Examples i can think of include:

- `youcube_playback_ended`
- `youcube_playing`
- `youcube_progress`
- `youcube_status`

**Comment by Commandcracker** [comment]
Sounds like a good idea, this will defiantly be implemented at some point.

**Comment by Commandcracker** [comment]
Reference: [os.queueEvent](https://tweaked.cc/module/os.html#v:queueEvent)
adding some parameters like the URL or some sort of tracking ID might also bee a good idea.
_([websocket_message](https://tweaked.cc/event/websocket_message.html))_

**Comment by Commandcracker** [comment]
https://github.com/Commandcracker/YouCube#events
