### ISSUE TITLE
YouCube does not support CC with Computronics

### ISSUE THREAD

**Issue by EmmaKnijn** [Commandcracker/YouCube#90]
### Description

YouCube will throw an error trying to start with a Computronics Tape Drive next to it

### Reproduction steps

1. Open 1.12.2 Minecraft with CC:T and Computronics
2. Place setup like in the second screenshot and place a tape inside
3. Run YouCube
4. Observe error

### Screenshots

![javaw_yTFER9j1pS](https://user-images.githubusercontent.com/64010592/209479731-816e2fa5-280c-4306-a311-3511f2c7cef7.png)
![javaw_h0lmUum4Tg](https://user-images.githubusercontent.com/64010592/209479732-5724e6ae-457c-4d45-b36e-8aaa43c81fc0.png)
![javaw_8cfAkKOgzC](https://user-images.githubusercontent.com/64010592/209479733-ffb0ec48-5b5f-4b15-87b3-474fa5bdd9c6.png)

**Comment by Commandcracker** [comment]
remove all speakers, the detection is a bit wrong
